### ISSUE TITLE
The benchmark run on a single node other than a cluster of multiple nodes?

### ISSUE THREAD

**Issue by kiwenlau** [cbcrg/docker-benchmarks#4]
I've read the paper [The impact of Docker containers on the performance of genomic pipelines](https://peerj.com/articles/1273/)

The paper said "The tests were executed using a cluster node HP BL460c Gen8 with 12 cpus Intel Xeon X5670 (2.93 GHz), 96 GB of RAM and running on Scientific Linux 6.5 (kernel 2.6.32-431.29.2.el6.x86 64)."

As I under stand it, all benchmarks run on a single node(**HP BL460c Gen8**) other than on a cluster of multiple nodes. 

Is it right?

Thank you!

**Comment by pditommaso** [comment]
Yes, it says _a cluster node_ i.e. a single cluster computational node.
